# Generated by Django 5.2.8 on 2025-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseemergencycontact',
            name='name',
        ),
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='event_types',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='last_name',
            field=models.CharField(),
        ),
    ]
