# Generated by Django 5.2.8 on 2025-12-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0002_remove_enterpriseemergencycontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
