# Generated by Django 5.2.8 on 2025-12-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0003_alter_enterpriseemergencycontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
