# Generated by Django 5.2.9 on 2025-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0004_alter_enterpriseemergencycontact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='event_types',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
