# Generated by Django 5.2.9 on 2025-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0005_alter_enterpriseemergencycontact_event_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseemergencycontact',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
