# Generated by Django 6.0 on 2025-12-10 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsutra_app', '0007_contact_eventnotificationgroup_eventtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+44-9564916773'. Up to 15 digits allowed.", regex='^\\+?\\d[\\d-]{8,14}\\d$')]),
        ),
    ]
